// Game configuration constants
export const GAME_CONFIG = {
    CANVAS_WIDTH: 800,
    CANVAS_HEIGHT: 700,
    UI_HEIGHT: 46,
    CEILING_Y: 65,
    SPIKE_HEIGHT: 25,
    PLAYER_WIDTH: 32,
    PLAYER_HEIGHT: 40,
    PLAYER_SPEED: 4.5,
    PLAYER_INVULNERABLE_FRAMES: 90,
    LOW_TIME_THRESHOLD: 10,
    LOW_LIVES_THRESHOLD: 1,
    HARPOON_SPEED: 8,
    POWER_WIRE_DURATION: 300,
    POWERUP_DROP_CHANCE: 0.05,
    AUTO_GUN_DROP_CHANCE: 0.005,
    TIME_FREEZE_DURATION: 240,
    SLOW_MO_DURATION: 300,
    SLOW_MO_FACTOR: 0.6,
    AUTO_GUN_DURATION: 360,
    AUTO_GUN_FIRE_RATE: 12,
    BULLET_SPEED: 10,
    POWER_WIRE_DROP_CHANCE: 0.015,
    POWER_WIRE_DROP_COOLDOWN: 240,
    POWER_WIRE_MAX_DROPS_PER_LEVEL: 2,
    DROP_LIFETIME: 600,
    TOTAL_LEVELS: 36,
    LEVELS_PER_PAGE: 5,
    BASE_TIME: 60,
    TIME_BONUS_PER_5_LEVELS: 5,
    SCORE_PER_BUBBLE_SIZE: 100,
    COMBO_HIT_THRESHOLD: 3,
    COMBO_BONUS: 250,
    TIME_BONUS_PER_SEC: 30,
    CEILING_SPIKE_BONUS: 150
};

export const BUBBLE_SIZES = {
    1: { radius: 12, bounceSpeed: 10.925 },
    2: { radius: 20, bounceSpeed: 12.0175 },
    3: { radius: 28, bounceSpeed: 13.11 },
    4: { radius: 40, bounceSpeed: 14.2025 }
};
