// Translations
export const translations = {
    de: {
        mainTitle: "bubblebyte",
        menuPlay: "spielen",
        menuSelectLevel: "level wählen",
        menuSettings: "einstellungen",
        menuStats: "statistik",
        settingsTitle: "> einstellungen",
        statsTitle: "> statistik",
        menuBack: "zurück",
        menuHintTitle: "> steuerungen",
        menuHintMove: "bewegen: ← → / a d",
        menuHintShoot: "schießen: space / ↑",
        menuHintPause: "pause: tab",
        progressTitle: "> fortschritt",
        highestLevelLabel: "höchstes level:",
        highScoreLabel: "höchste punktzahl:",
        selectLevelTitle: "> level wählen",
        startNewGame: "neues spiel starten",
        resetProgress: "fortschritt zurücksetzen",
        languageToggle: "sprache: deutsch",
        musicOn: "musik: an",
        musicOff: "musik: aus",
        sfxOn: "sfx: an",
        sfxOff: "sfx: aus",
        fpsOn: "fps: an",
        fpsOff: "fps: aus",
        level: "level",
        score: "score",
        lives: "leben",
        time: "zeit",
        status: "status",
        statusReady: "bereit",
        statusHit: "getroffen",
        statusFreeze: "zeitstopp",
        statusSlowMo: "zeitlupe",
        statusAutoGun: "auto-feuer",
        statusCrushed: "zerquetscht",
        bonusCombo: "combo bonus",
        bonusTime: "zeit bonus",
        bonusCeiling: "spike bonus",
        bonusSpike: "spike bonus",
        ready: "bereit machen!",
        dead: "Du bist tot",
        lifeLost: "Du bist tot",
        restarting: "neustart...",
        gameOver: "game over!",
        finalScore: "score:",
        levelReached: "level:",
        mainMenu: "hauptmenü",
        playAgain: "nochmal spielen",
        paused: "pausiert",
        resume: "fortsetzen",
        restartLevel: "level neustarten",
        unlocked: "[freigeschaltet]",
        locked: "[gesperrt]",
        resetConfirm: "gesamten fortschritt zurücksetzen? dies kann nicht rückgängig gemacht werden.",
        themeLabel: "theme:",
        themeClassic: "klassisch grün",
        themeCyber: "cyber blau",
        themeRetro: "retro bernstein",
        themeVoid: "void violett",
        themeSunset: "sonnenuntergang rot",
        themeOcean: "ozean cyan",
        themeNeon: "neon limette",
        themeGruvbox: "gruvbox dunkel",
        themeDracula: "dracula",
        themeNord: "nord",
        themeTokyoNight: "tokyo night",
        themeSolarizedDark: "solarized dunkel",
        themeRosePine: "rose pine",
        themePastelMint: "pastell minze",
        themePastelPeach: "pastell pfirsich",
        themePastelLavender: "pastell lavendel",
        themePastelSky: "pastell himmel",
        themePastelLemon: "pastell zitrone",
        themeGruvboxOrange: "gruvbox orange",
        themeDarkDracula: "dracula dunkel",
        themeNordAurora: "nord aurora",
        themeSoftRose: "soft rose",
        themeSoftSage: "soft sage",
        themeSoftSlate: "soft slate",
        themeMidnightBlue: "mitternachtsblau",
        themeForestNight: "waldnacht",
        themeMocha: "mocha",
        themeEmber: "ember",
        themeIce: "eisblau",
        prev: "< zurück",
        next: "weiter >",
        congratulations: "glückwunsch!",
        allLevelsComplete: "alle level geschafft!",
        levelStartMeta: "level start",
        prepareSystemsMeta: "systeme vorbereiten",
        livesLeftMeta: "verbleibende leben:",
        respawnMeta: "respawn läuft",
        campaignCompleteMeta: "kampagne abgeschlossen",
        levelClearedMeta: "level geschafft:",
        bonusLifeMeta: "bonus leben",
        crtOn: "crt-effekt: an",
        crtOff: "crt-effekt: aus",
        fullscreenOn: "vollbild: an",
        fullscreenOff: "vollbild: aus",
        powerWireActive: "power wire"
    },
    en: {
        mainTitle: "bubblebyte",
        menuPlay: "play",
        menuSelectLevel: "select level",
        menuSettings: "settings",
        menuStats: "stats",
        settingsTitle: "> settings",
        statsTitle: "> stats",
        menuBack: "back",
        menuHintTitle: "> controls",
        menuHintMove: "move: ← → / a d",
        menuHintShoot: "shoot: space / ↑",
        menuHintPause: "pause: tab",
        progressTitle: "> progress",
        highestLevelLabel: "highest level:",
        highScoreLabel: "highest score:",
        selectLevelTitle: "> select level",
        startNewGame: "start new game",
        resetProgress: "reset progress",
        languageToggle: "language: english",
        musicOn: "music: on",
        musicOff: "music: off",
        sfxOn: "sfx: on",
        sfxOff: "sfx: off",
        fpsOn: "fps: on",
        fpsOff: "fps: off",
        level: "level",
        score: "score",
        lives: "lives",
        time: "time",
        status: "status",
        statusReady: "ready",
        statusHit: "hit",
        statusFreeze: "time freeze",
        statusSlowMo: "slow mo",
        statusAutoGun: "auto gun",
        statusCrushed: "crushed",
        bonusCombo: "combo bonus",
        bonusTime: "time bonus",
        bonusCeiling: "spike bonus",
        bonusSpike: "spike bonus",
        ready: "get ready!",
        dead: "Dead",
        lifeLost: "you are dead",
        restarting: "restarting...",
        gameOver: "game over!",
        finalScore: "score:",
        levelReached: "level:",
        mainMenu: "main menu",
        playAgain: "play again",
        paused: "paused",
        resume: "resume",
        restartLevel: "restart level",
        unlocked: "[unlocked]",
        locked: "[locked]",
        resetConfirm: "reset all progress? this cannot be undone.",
        themeLabel: "theme:",
        themeClassic: "classic green",
        themeCyber: "cyber blue",
        themeRetro: "retro amber",
        themeVoid: "void violet",
        themeSunset: "sunset red",
        themeOcean: "ocean cyan",
        themeNeon: "neon lime",
        themeGruvbox: "gruvbox dark",
        themeDracula: "dracula",
        themeNord: "nord",
        themeTokyoNight: "tokyo night",
        themeSolarizedDark: "solarized dark",
        themeRosePine: "rose pine",
        themePastelMint: "pastel mint",
        themePastelPeach: "pastel peach",
        themePastelLavender: "pastel lavender",
        themePastelSky: "pastel sky",
        themePastelLemon: "pastel lemon",
        themeGruvboxOrange: "gruvbox orange",
        themeDarkDracula: "dark dracula",
        themeNordAurora: "nord aurora",
        themeSoftRose: "soft rose",
        themeSoftSage: "soft sage",
        themeSoftSlate: "soft slate",
        themeMidnightBlue: "midnight blue",
        themeForestNight: "forest night",
        themeMocha: "mocha",
        themeEmber: "ember",
        themeIce: "ice blue",
        prev: "< prev",
        next: "next >",
        congratulations: "congratulations!",
        allLevelsComplete: "all levels complete!",
        levelStartMeta: "level start",
        prepareSystemsMeta: "prepare systems",
        livesLeftMeta: "lives left:",
        respawnMeta: "respawn in progress",
        campaignCompleteMeta: "campaign complete",
        levelClearedMeta: "level cleared:",
        bonusLifeMeta: "bonus life",
        crtOn: "crt effect: on",
        crtOff: "crt effect: off",
        fullscreenOn: "fullscreen: on",
        fullscreenOff: "fullscreen: off",
        powerWireActive: "power wire"
    }
};

// Themes
export const themes = [
    {
        name: 'themeGruvbox',
        vars: {
            '--bg-dark': '#1d2021',
            '--bg-overlay': 'rgba(29, 32, 33, 0.98)',
            '--primary': '#ebdbb2',
            '--secondary': '#d5c4a1',
            '--accent': '#b8bb26',
            '--text-on-primary': '#1d2021',
            '--border-dim': '#504945',
            '--shadow': 'rgba(235, 219, 178, 0.4)',
            '--ui-bar-bg': 'rgba(29, 32, 33, 0.95)',
            '--ui-panel-bg': 'rgba(40, 40, 40, 0.7)',
            '--ui-strip-bg': 'rgba(50, 48, 47, 0.8)',
            '--ui-bonus-bg': 'rgba(35, 36, 34, 0.6)'
        }
    },
    {
        name: 'themeGruvboxOrange',
        vars: {
            '--bg-dark': '#1b1b1b',
            '--bg-overlay': 'rgba(27, 27, 27, 0.98)',
            '--primary': '#f2e5bc',
            '--secondary': '#d9c9a2',
            '--accent': '#fe8019',
            '--text-on-primary': '#1b1b1b',
            '--border-dim': '#5f564d',
            '--shadow': 'rgba(254, 128, 25, 0.35)',
            '--ui-bar-bg': 'rgba(27, 27, 27, 0.95)',
            '--ui-panel-bg': 'rgba(38, 38, 38, 0.74)',
            '--ui-strip-bg': 'rgba(48, 44, 40, 0.82)',
            '--ui-bonus-bg': 'rgba(34, 32, 30, 0.62)'
        }
    },
    {
        name: 'themeDarkDracula',
        vars: {
            '--bg-dark': '#1a1b26',
            '--bg-overlay': 'rgba(26, 27, 38, 0.98)',
            '--primary': '#f8f8f2',
            '--secondary': '#c9cbe3',
            '--accent': '#bd93f9',
            '--text-on-primary': '#1a1b26',
            '--border-dim': '#44475a',
            '--shadow': 'rgba(189, 147, 249, 0.4)',
            '--ui-bar-bg': 'rgba(26, 27, 38, 0.95)',
            '--ui-panel-bg': 'rgba(33, 35, 49, 0.75)',
            '--ui-strip-bg': 'rgba(42, 44, 62, 0.84)',
            '--ui-bonus-bg': 'rgba(29, 30, 42, 0.6)'
        }
    },
    {
        name: 'themeNordAurora',
        vars: {
            '--bg-dark': '#2a2f3a',
            '--bg-overlay': 'rgba(42, 47, 58, 0.98)',
            '--primary': '#eceff4',
            '--secondary': '#d8dee9',
            '--accent': '#88c0d0',
            '--text-on-primary': '#2a2f3a',
            '--border-dim': '#4c566a',
            '--shadow': 'rgba(136, 192, 208, 0.35)',
            '--ui-bar-bg': 'rgba(42, 47, 58, 0.95)',
            '--ui-panel-bg': 'rgba(52, 58, 71, 0.72)',
            '--ui-strip-bg': 'rgba(60, 67, 82, 0.82)',
            '--ui-bonus-bg': 'rgba(45, 51, 63, 0.62)'
        }
    },
    {
        name: 'themeMidnightBlue',
        vars: {
            '--bg-dark': '#111827',
            '--bg-overlay': 'rgba(17, 24, 39, 0.98)',
            '--primary': '#e5edff',
            '--secondary': '#c2d3ff',
            '--accent': '#60a5fa',
            '--text-on-primary': '#111827',
            '--border-dim': '#334155',
            '--shadow': 'rgba(96, 165, 250, 0.34)',
            '--ui-bar-bg': 'rgba(17, 24, 39, 0.95)',
            '--ui-panel-bg': 'rgba(28, 38, 58, 0.72)',
            '--ui-strip-bg': 'rgba(36, 48, 72, 0.84)',
            '--ui-bonus-bg': 'rgba(23, 33, 50, 0.6)'
        }
    },
    {
        name: 'themeForestNight',
        vars: {
            '--bg-dark': '#121a16',
            '--bg-overlay': 'rgba(18, 26, 22, 0.98)',
            '--primary': '#e7f0df',
            '--secondary': '#c9dbc0',
            '--accent': '#7fb069',
            '--text-on-primary': '#121a16',
            '--border-dim': '#3e5245',
            '--shadow': 'rgba(127, 176, 105, 0.34)',
            '--ui-bar-bg': 'rgba(18, 26, 22, 0.95)',
            '--ui-panel-bg': 'rgba(29, 40, 34, 0.72)',
            '--ui-strip-bg': 'rgba(37, 49, 42, 0.84)',
            '--ui-bonus-bg': 'rgba(24, 35, 29, 0.6)'
        }
    },
    {
        name: 'themeMocha',
        vars: {
            '--bg-dark': '#2b211b',
            '--bg-overlay': 'rgba(43, 33, 27, 0.98)',
            '--primary': '#f4e7d8',
            '--secondary': '#ddc8b2',
            '--accent': '#d18f5a',
            '--text-on-primary': '#2b211b',
            '--border-dim': '#6e5546',
            '--shadow': 'rgba(209, 143, 90, 0.35)',
            '--ui-bar-bg': 'rgba(43, 33, 27, 0.95)',
            '--ui-panel-bg': 'rgba(57, 44, 36, 0.72)',
            '--ui-strip-bg': 'rgba(67, 52, 42, 0.84)',
            '--ui-bonus-bg': 'rgba(49, 38, 31, 0.6)'
        }
    },
    {
        name: 'themeEmber',
        vars: {
            '--bg-dark': '#231315',
            '--bg-overlay': 'rgba(35, 19, 21, 0.98)',
            '--primary': '#ffe3dc',
            '--secondary': '#ffbfb0',
            '--accent': '#ff6b4a',
            '--text-on-primary': '#231315',
            '--border-dim': '#6a3a3f',
            '--shadow': 'rgba(255, 107, 74, 0.34)',
            '--ui-bar-bg': 'rgba(35, 19, 21, 0.95)',
            '--ui-panel-bg': 'rgba(49, 28, 30, 0.72)',
            '--ui-strip-bg': 'rgba(60, 35, 37, 0.84)',
            '--ui-bonus-bg': 'rgba(42, 23, 25, 0.6)'
        }
    },
    {
        name: 'themeIce',
        vars: {
            '--bg-dark': '#0f1d24',
            '--bg-overlay': 'rgba(15, 29, 36, 0.98)',
            '--primary': '#e8fbff',
            '--secondary': '#c5eef8',
            '--accent': '#67d6ff',
            '--text-on-primary': '#0f1d24',
            '--border-dim': '#356274',
            '--shadow': 'rgba(103, 214, 255, 0.34)',
            '--ui-bar-bg': 'rgba(15, 29, 36, 0.95)',
            '--ui-panel-bg': 'rgba(25, 44, 53, 0.72)',
            '--ui-strip-bg': 'rgba(34, 56, 67, 0.84)',
            '--ui-bonus-bg': 'rgba(21, 38, 46, 0.6)'
        }
    },
    {
        name: 'themeSoftRose',
        vars: {
            '--bg-dark': '#2c2430',
            '--bg-overlay': 'rgba(44, 36, 48, 0.98)',
            '--primary': '#ffeef6',
            '--secondary': '#f5cfe0',
            '--accent': '#f38ba8',
            '--text-on-primary': '#2c2430',
            '--border-dim': '#7a5c70',
            '--shadow': 'rgba(243, 139, 168, 0.34)',
            '--ui-bar-bg': 'rgba(44, 36, 48, 0.95)',
            '--ui-panel-bg': 'rgba(56, 46, 61, 0.72)',
            '--ui-strip-bg': 'rgba(68, 56, 74, 0.84)',
            '--ui-bonus-bg': 'rgba(49, 40, 54, 0.6)'
        }
    },
    {
        name: 'themeSoftSage',
        vars: {
            '--bg-dark': '#1f2a24',
            '--bg-overlay': 'rgba(31, 42, 36, 0.98)',
            '--primary': '#e9f5ea',
            '--secondary': '#cbe4cf',
            '--accent': '#9ac7a0',
            '--text-on-primary': '#1f2a24',
            '--border-dim': '#5f7a67',
            '--shadow': 'rgba(154, 199, 160, 0.34)',
            '--ui-bar-bg': 'rgba(31, 42, 36, 0.95)',
            '--ui-panel-bg': 'rgba(41, 54, 46, 0.72)',
            '--ui-strip-bg': 'rgba(50, 65, 56, 0.84)',
            '--ui-bonus-bg': 'rgba(35, 47, 40, 0.6)'
        }
    },
    {
        name: 'themeSoftSlate',
        vars: {
            '--bg-dark': '#242936',
            '--bg-overlay': 'rgba(36, 41, 54, 0.98)',
            '--primary': '#edf2ff',
            '--secondary': '#cfd8ef',
            '--accent': '#a6b6d9',
            '--text-on-primary': '#242936',
            '--border-dim': '#626b82',
            '--shadow': 'rgba(166, 182, 217, 0.34)',
            '--ui-bar-bg': 'rgba(36, 41, 54, 0.95)',
            '--ui-panel-bg': 'rgba(47, 54, 69, 0.72)',
            '--ui-strip-bg': 'rgba(57, 64, 81, 0.84)',
            '--ui-bonus-bg': 'rgba(41, 47, 60, 0.6)'
        }
    }
];
